export const currencyData = [
  {
    currency: "AED",
    symbol: "د.إ",
    name: "UAE Dirham",
    country: "UAE",
  },
  {
    currency: "AFN",
    symbol: "Af",
    name: "Afghani",
    country: "Afghanistan",
  },
  {
    currency: "ALL",
    symbol: "L",
    name: "Lek",
    country: "Albania",
  },
  {
    currency: "AMD",
    symbol: "Դ",
    name: "Armenian Dram",
    country: "Armenia",
  },
  {
    currency: "AOA",
    symbol: "Kz",
    name: "Kwanza",
    country: "Angola",
  },
  {
    currency: "ARS",
    symbol: "$",
    name: "	Australian Dollar",
    country: "Australia",
  },
  {
    currency: "ARS",
    symbol: "$",
    name: "	Australian Dollar",
    country: "Kiribati",
  },
  {
    currency: "ARS",
    symbol: "$",
    name: "	Australian Dollar",
    country: "Coconut Islands",
  },
  {
    currency: "ARS",
    symbol: "$",
    name: "	Australian Dollar",
    country: "Nauru",
  },
  {
    currency: "ARS",
    symbol: "$",
    name: "	Australian Dollar",
    country: "Tuvalu",
  },
  {
    currency: "AWG",
    symbol: "ƒ",
    name: "	Aruban Guilder/Florin",
    country: "Aruba",
  },
  {
    currency: "AZN",
    symbol: "ман",
    name: "	Azerbaijanian Manat",
    country: "Azerbaijan",
  },
  {
    currency: "BAM",
    symbol: "КМ",
    name: "	Konvertibilna Marka",
    country: "Bosnia and Herzegovina",
  },
  {
    currency: "BBD",
    symbol: "$",
    name: "	Barbados Dollar",
    country: "Barbados",
  },
  {
    currency: "BDT",
    symbol: "৳",
    name: "	Taka",
    country: "Bangladesh",
  },
  {
    currency: "BGN",
    symbol: "лв",
    name: "	Bulgarian Lev",
    country: "Bulgaria",
  },
  {
    currency: "BHD",
    symbol: "ب.د",
    name: "	Bahraini Dinar",
    country: "Bahrain",
  },
  {
    currency: "BIF",
    symbol: "₣",
    name: "	Burundi Franc",
    country: "Burundi",
  },
  {
    currency: "BMD",
    symbol: "$",
    name: "	Bermudian Dollar",
    country: "Bermuda",
  },
  {
    currency: "BND",
    symbol: "$",
    name: "	Brunei Dollar",
    country: "Brunei",
  },
  {
    currency: "BND",
    symbol: "$",
    name: "	Brunei Dollar",
    country: "Singapore",
  },
  {
    currency: "BOB",
    symbol: "Bs.",
    name: "	Boliviano",
    country: "Bolivia",
  },
  {
    currency: "BRL",
    symbol: "R$",
    name: "	Brazilian Real",
    country: "Brazil",
  },
  {
    currency: "BSD",
    symbol: "$",
    name: "	Bahamian Dollar",
    country: "Bahamas",
  },
  {
    currency: "BTN",
    symbol: "",
    name: "	Ngultrum",
    country: "Bhutan",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BYN",
    symbol: "Br",
    name: "Belarusian Ruble",
    country: "Belarus",
  },
  {
    currency: "BZD",
    symbol: "$",
    name: "Belize Dollar",
    country: "Belize",
  },
  {
    currency: "CAD",
    symbol: "$",
    name: "Canadian Dollar",
    country: "Canada",
  },
  {
    currency: "CDF",
    symbol: "₣",
    name: "Congolese Franc",
    country: "Congo (Kinshasa)",
  },
  {
    currency: "CHF",
    symbol: "₣",
    name: "Swiss Franc",
    country: "Lichtenstein",
  },
  {
    currency: "CHF",
    symbol: "₣",
    name: "Swiss Franc",
    country: "Switzerland",
  },
  {
    currency: "CLP",
    symbol: "$",
    name: "Chilean Peso",
    country: "Chile",
  },
  {
    currency: "CNY",
    symbol: "¥",
    name: "Yuan",
    country: "China",
  },
  {
    currency: "COP",
    symbol: "$",
    name: "Colombian Peso",
    country: "Colombia",
  },
  {
    currency: "CRC",
    symbol: "₡",
    name: "Costa Rican Colon",
    country: "Costa Rica",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BWP",
    symbol: "P",
    name: "Pula",
    country: "Botswana",
  },
];
